### ISSUE TITLE
Add combined import file

### ISSUE THREAD

**Issue by yuriy-fix** [vaadin/vaadin-ordered-layout#10]
People were willing to see combined import file, like `vaadin-ordered-layout.html` along with two separated files for layouts elements.

**Comment by tomivirkki** [comment]
Should be called `all-imports.html` to align with rest of our elements.

**Comment by samiheikki** [comment]
Relates to https://github.com/vaadin/vaadin-core/issues/147

**Comment by web-padawan** [comment]
The file now exists and is called `index.html` (also published to npm as `index.js`).
