### ISSUE TITLE
Add a dedicated scrolling container to vaadin-scroller

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-ordered-layout#102]
The scroller component's own size should not be affected by its content. The current structure makes it difficult to build, for instance, layouts with a header/footer and a Scroller in between. Example:

```java
@Route("layout")
public class LayoutRoute extends VerticalLayout {
    public LayoutRoute(){
        setSizeFull();
        Div header = new Div();
        header.setWidth("100%");
        header.setHeight("56px");
        header.getElement().getStyle().set("background-color", "yellow");
//        header.getElement().getStyle().set("flex-shrink", "0");
        add(header);

        Div left = new Div();
        left.setWidth("200px");
        left.setHeight("100%");
        left.getElement().getStyle().set("background-color", "blue");
        left.getElement().getStyle().set("flex-shrink", "0");

        VerticalLayout content = new VerticalLayout();
        content.setWidthFull();

        Scroller scroller = new Scroller();
        scroller.setSizeFull();
        scroller.setContent(content);

        Div right = new Div();
        right.setWidth("200px");
        right.setHeight("100%");
        right.getElement().getStyle().set("background-color", "red");
        right.getElement().getStyle().set("flex-shrink", "0");

        HorizontalLayout hl = new HorizontalLayout(left, scroller, right);
        hl.setSizeFull();
        addAndExpand(hl);

        Div footer = new Div();
        footer.setWidth("100%");
        footer.setHeight("56px");
        footer.getElement().getStyle().set("background-color", "yellow");
        footer.getElement().getStyle().set("flex-shrink", "0");
        add(footer);

        for(int i=0; i<100; i++){
            content.add(new TextField());
        }
    }
}
```

You'd either need to add `overflow: hidden` to the parent layout _or_ have the Scroller be absolutely positioned and wrapped inside of another container to have the layout working as expected.

Fix this by doing the wrapping inside the Sroller's own shadow root instead:
```html
<vaadin-scroller>
  # shadow root
    <div style="position: relative; width: 100%; height: 100%">
      <div style="position: absolute; width: 100%; height: 100%; overflow: auto">
        <slot>
```

**Comment by jouni** [comment]
The additional HorizontalLayout, which contains the left, scroll, and right components is IMO not a usual layout configuration. I would expect there to only be header, scroller, and footer. That configuration works fine as is.

Also, the complex nested structure is not the only way to fix the full example. Adding `min-height: 0;` for the `hl` layout solves it as well, but I’m not sure if we can introduce a default min-width and min-height for our layouts?

All in all, I think we shouldn’t complicate the Scroller implementation. Offering copy-pasteable examples of common layout configs is IMO the better solution.

**Comment by tomivirkki** [comment]
Yeah this is probably outdated, closing.
