### ISSUE TITLE
Change the wording of custom css properties.

### ISSUE THREAD

**Issue by YuriyVaadin** [vaadin/vaadin-ordered-layout#11]
Some of DX/UX tests participants were willing not to have words `column` and `row` in custom css properties for gaps (`--vaadin-vertical-layout-row-gap` and `--vaadin-horizontal-layout-column-gap`). Should we remove those?

**Comment by jouni** [comment]
Those are probably redundant, as the layout name (prefix) should already indicate in which place the gaps will end up.

Okay for me to chagne to `--vaadin-vertical-layout-gap` and `--vaadin-horizontal-layout-gap`.
