### ISSUE TITLE
Introduce combined custom css property.

### ISSUE THREAD

**Issue by YuriyVaadin** [vaadin/vaadin-ordered-layout#12]
Can we add one combined custom css property for customising gaps between items in both layouts?
Like `vaadin-ordered-layout-gap`?

**Comment by jouni** [comment]
I don’t think this is a high priority. 1 line vs 2 lines of CSS. And I expect that in most real-world cases the designer wants to set different values for these.

**Comment by web-padawan** [comment]
This is no longer relevant on `master`, therefore I am closing this issue.
Feel free to reopen if we decide to re-implement CSS custom property API for gaps in the future.
