### ISSUE TITLE
Overflow in nested layouts with smaller gaps

### ISSUE THREAD

**Issue by heruan** [vaadin/vaadin-ordered-layout#14]
If I place a vertical layout with a smaller gap inside another, its content overflows the parent's bounding box: https://jsfiddle.net/heruan/xus5x3jf/1/

<img width="339" alt="screen shot 2017-11-27 at 18 59 40" src="https://user-images.githubusercontent.com/851745/33281369-5014165a-d3a5-11e7-8be9-748cdafc10c6.png">

Similar issue with the horizontal layout, which overflows on the left.

**Comment by heruan** [comment]
Didn't notice at first a inner `<div id="layout">` was introduced, which is the actual element overflowing. Plus, with it it's not possibile to treat the host element as the flex container.

I've removed it and adjusted the style in [heruan/vaadin-ordered-layout#remove-div](https://github.com/heruan/vaadin-ordered-layout/tree/remove-div) and all is working as expected: https://jsfiddle.net/heruan/xus5x3jf/3/

Is `#layout` it really necessary then?

**Comment by jouni** [comment]
> Is #layout really necessary then?

I’m also wondering the same. Currently, you can’t control flexing or alignment of the child elements.

**Comment by jouni** [comment]
That element is most probably needed only for the negative margins to offset the gap.

**Comment by heruan** [comment]
In #15 I'm targeting first and last child of slot setting margins to zero, instead offsetting on the container parent. Seems working, am I missing any side effects?

**Comment by web-padawan** [comment]
@heruan pay attention to that `last-child` won't work if you pass a `<template>` tag. Currently, the `dom-if` and `dom-repeat` templates stamp their content above themselves, so in this case the template would be the actual last child from the CSS selector point of view.

**Comment by heruan** [comment]
@web-padawan Right, I knew I was missing something 😄 What about targeting the last *visible* element? `dom-repeat` sets its `display` to `none`, but in general the last child to have zero bottom margin should be the last visible one.

**Comment by web-padawan** [comment]
@heruan there is no way to target last visible child with CSS, that's what I mean. This was already discussed in #8

**Comment by heruan** [comment]
@web-padawan Got it. Thank you for the clarification! I've investigated further on this issue than, and it seems that setting the display of the host to `block` instead of `flex`, fixes the overflow.

Will this be acceptable?

**Comment by heruan** [comment]
> there is no way to target last visible child with CSS

Would be acceptable marking the last visible element via JS then? E.g.

```js
class HorizontalLayoutElement extends Vaadin.ThemableMixin(Polymer.Element) {
  static get is() {
    return 'vaadin-horizontal-layout';
  }

  static get version() {
    return '1.0.0-alpha3';
  }

  ready() {
    super.ready();
    this.$.slot.addEventListener('slotchange', event => {
      var elements = this.$.slot.assignedNodes().filter(this.__isVisibleElement);
      if (elements.length > 0) {
        elements[elements.length - 1].setAttribute('last-visible', true);
      }
    });
  }

  __isVisibleElement(node) {
    return node.nodeType === Node.ELEMENT_NODE && node.offsetParent !== null;
  }
}
```

Then target `[last-visible]` to remove margin.

**Comment by tomivirkki** [comment]
Would [this branch](https://github.com/vaadin/vaadin-ordered-layout/tree/scoped-gap) work as expected?

**Comment by heruan** [comment]
@tomivirkki Seem like it works! https://jsfiddle.net/heruan/xus5x3jf/4/
