### ISSUE TITLE
Improve the API docs descriptions for the theme variants (that they technically set CSS properties)

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-ordered-layout#17]

**Comment by web-padawan** [comment]
Actually, none of the existing theme variations does it:
- `theme="gap-none"` overrides CSS properties
- `theme="margin"` just sets `margin` on the host element
- `theme="padding"` just sets `padding` on the host element

I documented the current behavior in #21 while working on demos.

**Comment by platosha** [comment]
Closed by #21

**Comment by jouni** [comment]
The basic idea for this change was as simple as:


**theme="margin"**
Adds default margin around the layout -> Apply the default amount of CSS margin for the host element (default: specified by the theme)

Just to make it somehow explicit that it sets the CSS `margin` property on the host element, nothing else. Maybe I’m being patronizing, but I personally felt I wanted to know what these actually do, without needing to dig it up from the source code.

**Comment by web-padawan** [comment]
@jouni I see your point. My description added in #21 might be a bit incomplete so I will make it more explicit.
