### ISSUE TITLE
Make negative margin not occupy space

### ISSUE THREAD

**Issue by heruan** [vaadin/vaadin-ordered-layout#27]
~~The host `overflow` property should be set to `hidden`, to avoid the negative margin of the inner container to occupy space.~~

The negative margin applied on the flex container to compensate the margin of its first and last children occupies space, thus making scrollbars appear if near the viewport edges.

**Comment by jouni** [comment]
I really dislike the idea that overflow would be hidden by default. We had that in Vaadin Framework 6, and it caused a lot of gray hair for designers.

**Comment by heruan** [comment]
Didn't think of side effects, I rephrased to address the real issue!

**Comment by tomivirkki** [comment]
Would [this kind of fix](https://github.com/vaadin/vaadin-ordered-layout/tree/margin-overflow) do the trick?

**Comment by heruan** [comment]
I cannot replicate anymore with master, i.e. no scrollbars appearing with the negative margin. Closing this for now, I'll reopen if needed.

**Comment by tomivirkki** [comment]
The problem is still there, reopening

**Comment by jouni** [comment]
Can we have a jsbin/fiddle for this?

**Comment by heruan** [comment]
Confirmed on master: https://jsfiddle.net/heruan/tc8vnf0j/

You can see the overflow scrolling down the result frame.

**Comment by jouni** [comment]
Seriously, I have no idea how to fix this, other than `overflow: hidden` on the host or #layout element.

**Comment by heruan** [comment]
Seems like the problem with `:last-child` is with templated elements (e.g. `dom-repeat`, `dom-if`) which place themselves as the last element. Otherwise, targeting `:fisrt-child` and `:last-child` setting their margin to zero would work (and would be more correct, in my opinion).

Why not supporting templates in a different slot, so that we know they'll be the last element and we can target the `:nth-last-child(2)`?

**Comment by jouni** [comment]
I tried another approach, and it seems like it might work. Basically, just using a negative margin for the left/top edge of the layout doesn’t cause the overflow to trigger: http://jsbin.com/cayukekuda/edit?html,css,output

**Comment by tomivirkki** [comment]
Nice find @jouni! Prototype at "margin-overflow" branch

**Comment by jouni** [comment]
I don’t think it even needs the pseudo-element, the margin can still be in the `#layout` element.

**Comment by heruan** [comment]
The branch is working very well, it seems: https://jsfiddle.net/heruan/tc8vnf0j/1/

**Comment by heruan** [comment]
Don't hate me! I'm testing the new branch on my app layout and seems like an horizontal-layout with padding inside a vertical layout without gaps gets the top padding disappear: 

https://jsfiddle.net/heruan/tc8vnf0j/2/

**Comment by jouni** [comment]
Quite the opposite – you’re one of the best contributors we’ve ever had, providing valuable feedback constantly!

I actually bumped on the same issue, almost at the same time! Not exactly sure how to fix, yet, but your suggestion might work. But only if `theme="padding"` is moved to the parent layout. Having it on the child layout is not fixable.

**Comment by heruan** [comment]
I'm testing my app with the diff I posted (don't know if you replied before my update with the diff) and all the layout nesting structure seems to stay put; I'll test more thoroughly in the morning, to see if there are any side effects.

**Comment by jouni** [comment]
I already have a fix for that particular case in my current WIP prototype. I’ll share it tomorrow as well.

**Comment by jouni** [comment]
My simplified #FFS version is now in the [default-behavior](https://github.com/vaadin/vaadin-ordered-layout/tree/default-behavior) branch (silly name, the implementation got out of hand). Feel free to test it in your use case.

**Comment by tomivirkki** [comment]
Removing the internal layout container re-introduces the issues with layout gap CSS property scope: https://jsfiddle.net/udnk6a4u/

**Comment by jouni** [comment]
Right, that is very true. I was trying to remember that particular case which required some special care, but didn’t. Damn.
