### ISSUE TITLE
Default margins on an element override gap margin in ShadyCSS

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-ordered-layout#28]
If you place a `<vaadin-button>` (using Valo theme) in a vaadin ordered layout, the default margin on the button’s host element override the gap margin on polyfilled browsers using ShadyCSS.

**Comment by web-padawan** [comment]
@jouni I was unable to reproduce this issue with the master versions of `vaadin-button` and `vaadin-ordered-layout` in both IE11. Could you please provide an example code and the browser in which this can be confirmed?

**Comment by web-padawan** [comment]
I am unable to reproduce this issue with `1.0.0-alpha4` in IE11. Closing, feel free to reopen if you have a code snippet which demonstrates it is still valid.
