### ISSUE TITLE
Make it easy to add whitespace between the elements inside the layout (a.k.a. “spacing”)

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-ordered-layout#3]
For convenience, let’s consider adding attributes for defining the spacing between the elements in the layout.

For example:

```html
<!-- Add default spacing -->
<vaadin-vertical-layout spacing>
  ...
</vaadin-vertical-layout>

<!-- Set explicit spacing value -->
<vaadin-vertical-layout spacing="L">
  ...
</vaadin-vertical-layout>
```

The actual spacing sizes should be controllable with CSS/theme, e.g. 
```css
--vaadin-layout-spacing-xs: 4px;
--vaadin-layout-spacing-s: 8px;
--vaadin-layout-spacing-m: 16px;
--vaadin-layout-spacing-l: 32px;
--vaadin-layout-spacing-xl: 64px;
```

**Comment by Legioth** [comment]
Does `margin` an `spacing` in this case have the same meaning as in e.g. `VerticalLayout` in FW8, or would they have some different meaning? Is `margin` a sensible word to use in this context since it doesn't work the same way as `margin` in CSS?

**Comment by jouni** [comment]
That remains to be seen. This is not a finalized design by any means, just the starting point.

**Comment by jouni** [comment]
I mean, we should do some experiments and testing to figure those things out.

**Comment by jouni** [comment]
I mean, it could very well be that layouts do not need a `margin` concept, and instead we should have a `padding` concept for other containers, and layouts would only handle `spacing`.

**Comment by jouni** [comment]
I refined this issue to be only about spacing. We can open a new issue for margin/padding if needed.

**Comment by jouni** [comment]
I wrote a draft proposal from the Java perspective: https://github.com/vaadin/vaadin-ordered-layout-flow/issues/1#issuecomment-342169722

For the web component, I think it would translate to something like this:

```html
<vaadin-vertical-layout spacing="L" spacing-top="M" spacing-bottom="M">
  …
</vaadin-vertical-layout>
```

**Comment by heruan** [comment]
Would this be themable? Valo has some spacing variables, it'd be nice having the theme to control these values, for consistent spacing.

**Comment by jouni** [comment]
Yes, absolutely. Those spacing variables would control these directly.

**Comment by jouni** [comment]
I’m a bit concerned what we should do for vaadin-form-layout, and the row and column gaps we have there – we should probably align the layouts to use the same API?

Also, what about vaadin-split-layout? Would it make sense to introduce spacing for it as well (at some point in the future)?

**Comment by jouni** [comment]
@platosha had some good points about aligning the new layouts with the form layout (instead of the other way around). So here’s a take on that.

## Internal spacing a.k.a. gaps

The internal, in between children, spacing would be named like it is in the form layout, as a “gap” (column gap or row gap).

It would be similarly controllable with CSS custom properties, like `--vaadin-vertical-layout-row-gap` and `--vaadin-horizontal-layout-column-gap`. These would have some default values defined by the host elements, like `2em` (the same as in form layout), so they won’t inherit.

```css
/* vaadin-vertical-layout.html */
:host {
  --vaadin-vertical-layout-row-gap: 2em;
}

/* vaadin-horizontal-layout.html */
:host {
  --vaadin-vertical-layout-column-gap: 2em;
}
```

I’m proposing these would be **on by default**, and the developer would need to set the property to zero to disable it (or use a plain flex layout). **There would be no additional property/attribute to toggle this**.

**Question**: why don’t we use unprefixed property names like `--row-gap` and `--column-gap`? Is it just because the prevailing convention currently is to add prefixes?

## Outer spacing

The outer spacing (margin/padding) would be left for a theme to define, as it’s really just about adding padding/margin CSS properties for the element, which don’t really warrant a built-in feature that much.

Also, the different presets for the spacing size would make more sense as a theme feature, as the element should not dictate how many there could be, or how they are named.

## Apply spacing with a theme

These “theme classes” could be utility classes that work on any element, not just layouts (except the for the row/column gap). Just like many of the popular CSS frameworks work (like [Tachyons](http://tachyons.io/docs/layout/spacing/) for example).

Examples:
```html
<!-- Set padding and margin around the layout to M -->
<div theme="padding-m margin-m">...</div>

<!-- Set the gap to M (applies only for vertical/horizontal layout) -->
<vaadin-vertical-layout theme="gap-m">...</vaadin-vertical-layout>

<!-- Set vertical (top and bottom) padding to XL -->
<div theme="padding-vertical-xl">...</div>

<!-- Set top padding top to XS -->
<div theme="padding-top-xs">...</div>
```

The developer could include these to any style scope by importing and including the “valo-spacing” style module:

```html
<link rel="import" href="bower_components/vaadin-valo-theme/spacing.html">

<custom-style>
  <style include="valo-spacing"></style>
</custom-style>
```

**Comment by jouni** [comment]
Alright, circling back once again from [the Java side](https://github.com/vaadin/vaadin-ordered-layout-flow/issues/1#issuecomment-343393764), here’s hopefully a close-to-final spec for this feature:

### Gaps

Gaps are on by default and controlled with CSS custom properties, as with `vaadin-form-layout`.

```css
--vaadin-vertical-layout-row-gap: 2em;
--vaadin-horizontal-layout-column-gap: 2em;
```

The core styles of the layout include one built-in “theme variation” which disables the gaps:

```html
<vaadin-vertical-layout theme="gap-none">...</vaadin-vertical-layout>
```


### Margin and padding

Margin and padding are controlled completely by the theme. The core styles include one “catch-all” variant for both:

```css
:host([theme~="margin"]) {
  margin: 2em;
}

:host([theme~="padding"]) {
  padding: 2em;
}
```
