### ISSUE TITLE
Prototype new structure for ordered layout

### ISSUE THREAD

**Issue by web-padawan** [vaadin/vaadin-ordered-layout#30]
__Why__: the current implementation with the nested flex container does not quite meet the Flow team expectations and API requirements.

__What__:

- return back to the initial structure (host element is a flex container)
- drop custom CSS property fort gap
  - there should be no gap by default
  - user can apply gaps specified by theme
  - for custom gaps, CSS `margin` can be still used

**Comment by heruan** [comment]
> user can apply gaps specified by theme

How the theme may specify gaps?

**Comment by web-padawan** [comment]
@heruan I mean using something like `theme="spacing"`  to apply the default margin between items.

**Comment by heruan** [comment]
Sure, but I wonder *how* the margin could be set, i.e. the main issue with current release (only margin between inner items, not first/last).

**Comment by web-padawan** [comment]
@heruan We have a discussion on this today and decided to stick with `em` units for a moment. I added the demo illustrating how that CSS feature could be useful in f4508b5. Please check if it targets your question?

**Comment by heruan** [comment]
Thank you @web-padawan for asking feedback. I tried the new branch and it does not fix my main issue, which is trying to have a vertical layout with spacing which does not occupy space with its negative margins. E.g.

```html
<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1" />
  <title>vaadin-ordered-layout overflow</title>
  <script src="../../webcomponentsjs/webcomponents-lite.js"></script>

  <style>
    body {
      margin: 0;
    }
    vaadin-vertical-layout {
      background-color: #ddd;
      min-height: 100vh;
    }
  </style>
</head>

<body>
  <link rel="import" href="../../polymer/polymer.html">
  <link rel="import" href="../vaadin-horizontal-layout.html">
  <link rel="import" href="../vaadin-vertical-layout.html">

  <vaadin-vertical-layout theme="spacing">
    <div>Content</div>
  </vaadin-vertical-layout>

</body>
</html>
```

![layout-overflow](https://user-images.githubusercontent.com/851745/33998588-44255f7a-e0e8-11e7-9dc0-2f4932186ee6.gif)

If my use case is wrong/unsupported or if I'm missing obvious workarounds, please let me know 😄

**Comment by tomivirkki** [comment]
@web-padawan The fix for scroll overflowing described here https://github.com/vaadin/vaadin-ordered-layout/issues/27#issuecomment-349987794
