### ISSUE TITLE
iron-list doesn't work inside vertical-layout

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/vaadin-ordered-layout#63]
**Forewarning**: I'm not sure whether this is an issue in the `vertical-layout` component or `iron-list`.
As I understand the `iron-list` component is not maintained by Vaadin so I can't say for sure where is the issue.
Sorry if it's not in the `vaadin-ordered-layout`. I will need assistance anyway in this issue to be able to create a ticket for `iron-list` if needed since I'm not familiar with client-side stuff.

I have a `vaadin-vertical-layout`  component. Let's say it's referenced as a `layout`.

Now I use the following code:
```
var templ = document.createElement('template');
templ.innerHTML="<span><template is='dom-if' if='[[item.__placeholder]]'>[[item.label]]</template><template is='dom-if' if='[[!item.__placeholder]]'>[[item.label]]</template></span>";
var list = document.createElement('iron-list');
list.appendChild(templ);
layout.appendChild(templ);
list.items=[{label: "bar"}]
```

The result is: nothing is shown in the browser.

Now if I use `div` instead of vaadin-vertical-layout` ( so `layout` is a `div` element) then the same code renders `bar` string as expected.

The original issue comes from Flow with server side component.
In Flow the `iron-list`  client side method `_assignModels` is redefined and it's expected to be called to trigger Flow engine.
But I see while debugging that the `_assignModels` method is never called if `vertical-layout` is used as a parent. 
And it's called multiple times if `div`  is used as a parent.

**Comment by heruan** [comment]
As per documentation of `iron-list`, it needs to be explicitly sized to appear i.e. having a defined `height` or being part of a Flexbox layout in an explicitly sized container.

**Comment by denis-anisimov** [comment]
Oh.......
That's quite unexpected for me.
But that's true. 
Our javadocs for `IronList` component even says that.

Thanks a lot for the tip.
