### ISSUE TITLE
Add a demo for vaadin-scroller component

### ISSUE THREAD

**Issue by Haprog** [vaadin/vaadin-ordered-layout#84]
There should be at least a simple demo for `<vaadin-scroller>` which could optionally also explain why the component exists and who it's meant for, just for avoiding confusion because now there is no demo for it.

Afaik initially the demo was intentionally left out since the scroller was not targeted for frontend devs atm but needed for the Java API implementation and for Vaadin Designer support. But the component may also become more useful to frontend first development if more features are added to it.

**Comment by web-padawan** [comment]
The demos will be removed during the Polymer 3 conversion as we stop using `vaadin-demo-helpers`.

There is a scroller demo in the new docs site (beta): https://vaadin.com/docs-beta/latest/ds/components/scroller/
