### ISSUE TITLE
TextField shrinks in Safari in weird way when used in VerticalLayout

### ISSUE THREAD

**Issue by mstahv** [vaadin/vaadin-ordered-layout#95]
Vaadin 14.0.2, latest Safari on desktop. With following code:

```
@Route
public class MainView extends VerticalLayout {
    public MainView() {
        add(new Span("It works!?"));
        add(new TextField());
        Grid<String> grid = new Grid<>();
        add(grid);
        expand(grid);
        setHeightFull();  
    }
}
```

Safari renders text field as a thin line when screen size is small:

<img width="856" alt="Screenshot 2019-09-03 at 12 50 42 " src="https://user-images.githubusercontent.com/1478052/64164289-9c337d80-ce4b-11e9-9ae3-49ee692a4f07.png">

With Chrome it looks as expected:

<img width="842" alt="Screenshot 2019-09-03 at 12 50 57 " src="https://user-images.githubusercontent.com/1478052/64164326-b2413e00-ce4b-11e9-8943-16a0f8646178.png">

**Comment by rolfsmeds** [comment]
Related: https://github.com/vaadin/vaadin-ordered-layout/issues/48

**Comment by rolfsmeds** [comment]
No longer reproducible in Safari 14.0.3.
